### ISSUE TITLE
Missing properties on Itemstack database

### ISSUE THREAD

**Issue by TBroz15** [syylaxx/RockWrap#1]
There are few missing itemstack properties like `keepOnDeath, lockMode, canDestroy, canPlaceOn` and dynamic properties. I may make a quick pr on this

**Comment by syylaxx** [comment]
❤️ Thanks, for the commit.

I made small changes to it:
Added your changes to `ItemStackManager().getObject()` and `ItemStackManager.getManager()` so those are updated aswell
